# Generated by Django 6.1.1 on 2026-09-22 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '3 Months', '6 Months', '12 Months'", max_length=100)),
                ('slug', models.SlugField(help_text="Used in the checkout URL, e.g. '3-months'.", max_length=100, unique=True)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, help_text='Short one-line description shown under the plan name.', max_length=255)),
                ('features', models.TextField(help_text='One feature per line. These render as a bullet list on the pricing card.')),
                ('badge', models.CharField(blank=True, help_text='e.g. STARTER, BEST VALUE, BEST COMMITMENT', max_length=40)),
                ('is_featured', models.BooleanField(default=False, help_text='Visually highlight this plan as the recommended option.')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers display first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'duration_months'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('main_goal', models.CharField(max_length=255)),
                ('training_experience', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('training_location', models.CharField(choices=[('HOME', 'Home'), ('GYM', 'Gym'), ('BOTH', 'Both')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card Payment'), ('FAWRY', 'Fawry'), ('VODAFONE_CASH', 'Vodafone Cash'), ('INSTAPAY', 'InstaPay')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coaching.coachingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
