# Generated by Django 6.1.1 on 2026-09-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_label', models.CharField(help_text="e.g. 'Ahmed, 28' or 'Client A' - never a fabricated name.", max_length=100)),
                ('before_image', models.ImageField(blank=True, upload_to='transformations/')),
                ('after_image', models.ImageField(blank=True, upload_to='transformations/')),
                ('goal', models.CharField(blank=True, max_length=150)),
                ('duration', models.CharField(blank=True, help_text="e.g. '12 Weeks'.", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Short, factual result description.', max_length=255)),
                ('testimonial', models.TextField(blank=True, help_text='A real client quote. Leave blank until a real one is provided.')),
                ('featured', models.BooleanField(default=False, help_text='Show as the large featured transformation with the before/after slider.')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers display first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
